### ISSUE TITLE
can you provide the teacher and student weights?

### ISSUE THREAD

**Issue by zhiweihu1103** [2018cx/SinKD#1]
Hi, folk. nice work, can you provide the teacher and student weights of Table 1?

![image](https://github.com/2018cx/SinKD/assets/17820697/c5cfb19a-baa9-4f06-91e8-ff216eee84d2)

**Comment by yuleiqin** [comment]
> Hi, folk. nice work, can you provide the teacher and student weights of Table 1?
> 
> ![image](https://private-user-images.githubusercontent.com/17820697/333819322-c5cfb19a-baa9-4f06-91e8-ff216eee84d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MDUxMDYsIm5iZiI6MTcxOTkwNDgwNiwicGF0aCI6Ii8xNzgyMDY5Ny8zMzM4MTkzMjItYzVjZmIxOWEtYmFhOS00ZjA2LTkxZTgtZmYyMTZlZWU4NGQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA3MjAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5YjVjNjJhMGNiMTlkYWUyOGJkOTc4ODcyNTE4MGY3ODUwNzhhN2NjOTA0YTNmOTY1NjkzMDdmMDU0ZjU2ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d0EMr4Ses4F-x94OhMscLQNBBXia-UKC-Ju2nRHOoEc)

Hi, sorry for the late reply.
The checkpoint for the teacher model is attached below:
https://drive.google.com/file/d/1sBi35Dk8VJ7TU0warB6BL9QKx-in9Ww6/view?usp=drive_link

**Comment by yuleiqin** [comment]
> Hi, folk. nice work, can you provide the teacher and student weights of Table 1?
> 
> ![image](https://private-user-images.githubusercontent.com/17820697/333819322-c5cfb19a-baa9-4f06-91e8-ff216eee84d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTAxNDEsIm5iZiI6MTcxOTkwOTg0MSwicGF0aCI6Ii8xNzgyMDY5Ny8zMzM4MTkzMjItYzVjZmIxOWEtYmFhOS00ZjA2LTkxZTgtZmYyMTZlZWU4NGQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA4NDQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNDI4MGUyMjVmNmE4NGVkZWRjOTljNTg0ZjNlZDgzYWYyM2M3Nzg4YzJlOWZjZjQyZjNkMTkzNDgzZjZiYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cQN_H8m1Y-PyEa4wF2EckA5wOgcupnYz-oQZ5JsYx_c)

Let me know if you have more questions.

**Comment by zhiweihu1103** [comment]
How about the student model weights?

**Comment by zhiweihu1103** [comment]
further question is, how do you get the red box results?
![image](https://github.com/2018cx/SinKD/assets/17820697/652eba07-4d63-4248-8da1-c33373955486)

**Comment by yuleiqin** [comment]
> How about the student model weights?

The distilled student model for each task reported in the paper can be downloaded using the following link: https://drive.google.com/drive/folders/1BsA0VHKSa_-Bp5I7dQ2Ftk2q7cIyPrdC

**Comment by yuleiqin** [comment]
> further question is, how do you get the red box results? ![image](https://private-user-images.githubusercontent.com/17820697/344950954-652eba07-4d63-4248-8da1-c33373955486.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTYwMDMsIm5iZiI6MTcxOTkxNTcwMywicGF0aCI6Ii8xNzgyMDY5Ny8zNDQ5NTA5NTQtNjUyZWJhMDctNGQ2My00MjQ4LThkYTEtYzMzMzczOTU1NDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDEwMjE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlNzRmMjVmYjhhNjRmZmNjOTZjN2E0NTI5ZjA2NmYwMGIyNmE1MWRmYzVhNzUwN2Q5NTA1ZWQzZTc2MjczZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L13fSYDKL4iHoMz129HbQMxQW5T_EQjQ5Q4gfFVj2-w)

We directly quote them from their papers. (It is difficult to reproduce their results.)
